server:
  port: 8092
spring:
  application:
    name: service-customer

  datasource:
    url: jdbc:postgresql://localhost:5432/Customer
    username: postgres
    password: gustavo 22

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka/


