server:
  port: 8093

spring:
  application:
    name: service-shopping

  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: root
    password: gustavo 22

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka/