server:
  port: 8091

spring:
  application:
    name: service-product
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Producto;TrustServerCertificate=True
    username: sa
    password: gustavo 22

  jpa:
    hibernate:
      ddl-auto: update
